"""add crisis flag to messages

Revision ID: 605e113e09ef
Revises: be15c3158227
Create Date: 2026-06-17 09:12:28.549335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605e113e09ef'
down_revision: Union[str, Sequence[str], None] = 'be15c3158227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('crisis_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'crisis_flag')
    # ### end Alembic commands ###
