"""columns to store voice data

Revision ID: be15c3158227
Revises: f73d2d4ced42
Create Date: 2026-06-15 12:29:49.278074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be15c3158227'
down_revision: Union[str, Sequence[str], None] = 'f73d2d4ced42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('input_type', sa.String(), nullable=False))
    op.add_column('chat_messages', sa.Column('sentiment', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.add_column('chat_messages', sa.Column('dominant_emotion', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('transcription', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'transcription')
    op.drop_column('chat_messages', 'dominant_emotion')
    op.drop_column('chat_messages', 'sentiment_score')
    op.drop_column('chat_messages', 'sentiment')
    op.drop_column('chat_messages', 'input_type')
    # ### end Alembic commands ###
